export const CATEGORY_KEYWORDS  = {
  "Utilities": [
    "hydro",
    "water",
    "enmax",
    "shaw",
    "telus",
    "telus mobility",
    "rogers",
    "rogers wireless",
    "bell",
    "bell canada",
    "fido",
    "koodo",
    "virgin",
    "virgin plus",
    "freedom",
    "freedom mobile",
    "chatr",
    "public mobile",
    "eastlink",
    "sasktel",
    "videotron",
    "xplornet",
    "insurance",
    "loan",
    "student loan",
    "mortgage",
    "property tax",
    "waste",
    "garbage",
    "internet",
    "wifi",
    "wireless",
    "cell",
    "mobile",
    "phone bill",
    "landline",
    "electric",
    "power",
    "energy",
    "atco",
    "fortis",
    "gas bill",
    "utilities",
    "city of",
    "security",
    "adt",
    "vivint",
    "alarmforce",
    "camera",
    "doorbell",
    "home services",
    "calgary water",
    "calgary utilities",
    "enbridge",
    "direct energy",
    "epcor",
    "energyplus",
    "shaw direct",
    "bell mts",
    "rogers internet",
    "telus home",
    "utility bill",
    "shaw cable",
    "bell mobility",
    "rogers cable",
    "fortis alberta",
    "alberta utilities",
    "waste management",
    "alarm system",
    "powerstream",
    "hydro one",
    "city utilities",
    "utility connection",
    "phone plan",
    "data plan",
    "5g service"
  ],
  "Food & Drink": [
    "tim hortons",
    "subway",
    "mcdonald",
    "pizza",
    "burger",
    "boston pizza",
    "buffet",
    "restaurant",
    "liquor",
    "beer",
    "wine",
    "dairy queen",
    "jugo juice",
    "starbucks",
    "a&w",
    "wendys",
    "kfc",
    "popeyes",
    "taco bell",
    "five guys",
    "earls",
    "milestones",
    "the keg",
    "montana's",
    "joey",
    "cactus club",
    "dominos",
    "pizza hut",
    "panago",
    "harveys",
    "mary browns",
    "sushi",
    "pho",
    "shawarma",
    "bubble tea",
    "timmy",
    "cafe",
    "coffee",
    "barista",
    "brewery",
    "pub food",
    "fast food",
    "food court",
    "skip",
    "ubereats",
    "doordash",
    "grubhub",
    "delivery",
    "meal prep",
    "instacart",
    "groceries",
    "takeout",
    "restaurant supply",
    "catering",
    "snacks",
    "chips",
    "second cup",
    "good earth",
    "blenz",
    "oeb breakfast",
    "moxies",
    "original joes",
    "earls kitchen",
    "local public eatery",
    "cora",
    "dennys",
    "perkins",
    "humptys",
    "husky house",
    "swiss chalet",
    "east side marios",
    "montanas",
    "white spot",
    "smittys",
    "nandos",
    "edo japan",
    "pita pit",
    "mucho burrito",
    "booster juice",
    "freshii",
    "blaze pizza",
    "fatburger",
    "smashburger",
    "red robin",
    "olive garden",
    "mr sub",
    "second cup",
    "good earth cafe",
    "italiannis",
    "keg steakhouse",
    "wild rose brewery",
    "alley burger",
    "hudsons",
    "cowboys",
    "hudsons pub",
    "rosedale cafe",
    "SAMRU"
  ],
  "Transportation": [
    "uber",
    "lyft",
    "transit",
    "taxi",
    "bus",
    "gas",
    "petro",
    "co-op gas",
    "shell",
    "esso",
    "husky",
    "car wash",
    "parking",
    "vehicle",
    "auto",
    "mechanic",
    "car rental",
    "enterprise",
    "budget",
    "hertz",
    "aviation",
    "air canada",
    "westjet",
    "flair",
    "airplane",
    "train",
    "via rail",
    "greyhound",
    "carshare",
    "tire",
    "maintenance",
    "oil change",
    "tap transit",
    "presto",
    "compass",
    "my fare",
    "parking meter",
    "yyc airport",
    "park2go",
    "parknfly",
    "calgary transit",
    "uber eats",
    "taxi fare",
    "taxi line",
    "petrocan",
    "costco gas",
    "husky energy",
    "co-op car wash",
    "car detailing",
    "napa auto",
    "kal tire",
    "mr lube",
    "minute lube",
    "certified auto",
    "auto glass",
    "insurance repair",
    "yyc parking",
    "airport shuttle",
    "downtown parking",
    "street parking",
    "bus pass",
    "monthly transit",
    "car service",
    "vehicle repair",
    "autobody",
    "fuel station"
  ],
  "Shopping & Retail": [
    "walmart",
    "safeway",
    "freshco",
    "dollarama",
    "dollar tree",
    "giant tiger",
    "costco",
    "superstore",
    "no frills",
    "save on",
    "sobeys",
    "metro",
    "coop",
    "bulk barn",
    "canadian tire",
    "home depot",
    "lowes",
    "best buy",
    "london drugs",
    "staples",
    "ikea",
    "winners",
    "marshalls",
    "sport chek",
    "sephora",
    "shoppers drug",
    "hudson's bay",
    "bay",
    "gap",
    "old navy",
    "h&m",
    "zara",
    "uniqlo",
    "aritzia",
    "lululemon",
    "roots",
    "garage",
    "dynamite",
    "michaels",
    "indigo",
    "pet smart",
    "pet valu",
    "petland",
    "amazon",
    "ebay",
    "shein",
    "temu",
    "etsy",
    "aliexpress",
    "wish",
    "samsung store",
    "apple store",
    "google store",
    "electronics",
    "mall",
    "market",
    "thrift",
    "value village",
    "winners",
    "factory outlet",
    "boutique",
    "retail",
    "dollarstore",
    "hardware",
    "tools",
    "cleaning",
    "toys",
    "stationery",
    "home hardware",
    "leons",
    "the brick",
    "structube",
    "jysk",
    "sleep country",
    "visions electronics",
    "canadian appliance",
    "home sense",
    "urban barn",
    "the source",
    "mark's",
    "reitmans",
    "garage clothing",
    "sporting life",
    "decathlon",
    "clearly",
    "lenscrafters",
    "staples canada",
    "dollar giant",
    "canada computers",
    "the body shop",
    "sears",
    "shopperplus",
    "pharmasave",
    "rexall",
    "calgary coop",
    "save-on-foods",
    "hbc",
    "winners calgary",
    "sunridge mall",
    "chinook centre",
    "crossiron mills",
    "market mall",
    "southcentre",
    "nordstrom",
    "simons",
    "united furniture",
    "structube calgary"
  ],
  "Digital Services": [
    "apple",
    "apple music",
    "apple tv",
    "apple store",
    "icloud",
    "itunes",
    "google",
    "google play",
    "youtube",
    "youtube premium",
    "android",
    "gmail",
    "amazon",
    "amazon web",
    "amazon prime",
    "prime video",
    "affirm",
    "paypal",
    "meta",
    "facebook",
    "instagram",
    "linkedin",
    "dropbox",
    "canva",
    "adobe",
    "zoom",
    "microsoft",
    "office",
    "windows",
    "xbox",
    "outlook",
    "spotify",
    "netflix",
    "crave",
    "disney+",
    "paramount+",
    "twitch",
    "onlyfans",
    "patreon",
    "hulu",
    "max",
    "roku",
    "sling",
    "discord",
    "snapchat",
    "tiktok",
    "reddit",
    "bing",
    "yahoo",
    "stripe",
    "square",
    "cash app",
    "venmo",
    "coinbase",
    "crypto",
    "binance",
    "wealthsimple",
    "qtrade",
    "mint",
    "notion",
    "chatgpt",
    "openai",
    "midjourney",
    "deezer",
    "pandora",
    "audible",
    "kindle",
    "tesla app",
    "fitbit",
    "garmin",
    "nest",
    "ring",
    "smartthings",
    "alexa",
    "siri",
    "cortana",
    "bell fibe",
    "rogers ignite",
    "telus tv",
    "shaw bluecurve",
    "freedom app",
    "cbc gem",
    "paramount plus",
    "tubi",
    "pluto tv",
    "stacktv",
    "hayu",
    "iheartradio",
    "reddit premium",
    "x premium",
    "spotify family",
    "youtube music",
    "google one",
    "icloud storage",
    "apple arcade",
    "playstation plus",
    "xbox game pass",
    "steam wallet",
    "epic games",
    "ea play",
    "crunchyroll",
    "funimation",
    "canadian press",
    "substack",
    "medium",
    "vimeo",
    "zoom pro",
    "office365",
    "adobe cloud",
    "chatgpt plus",
    "midjourney plan",
    "canva pro",
    "notion ai",
    "dropbox plus",
    "onedrive",
    "paypal canada"
  ],
  "Entertainment": [
    "netflix",
    "spotify",
    "movie",
    "movies",
    "cinema",
    "theatre",
    "cineplex",
    "landmark",
    "amc",
    "imdb",
    "eventbrite",
    "ticketmaster",
    "ticket",
    "concert",
    "festival",
    "fair",
    "casino",
    "arcade",
    "bowling",
    "pool hall",
    "billiards",
    "golf",
    "mini golf",
    "paintball",
    "escape room",
    "karaoke",
    "bar",
    "pub",
    "club",
    "social",
    "sports",
    "game",
    "gamestop",
    "playstation",
    "xbox",
    "steam",
    "nintendo",
    "arena",
    "stadium",
    "movie pass",
    "streaming",
    "entertainment",
    "cowboys casino",
    "grey eagle casino",
    "pure casino calgary",
    "yyc concert",
    "stampede",
    "calgary stampede",
    "rodeos",
    "music fest",
    "saddledome",
    "scotiabank saddledome",
    "mcmahon stadium",
    "heritage park",
    "telus spark",
    "calgary zoo",
    "bow habitat",
    "calaway park",
    "bowness park",
    "devonian gardens",
    "arts commons",
    "glenbow museum",
    "the rec room",
    "cineplex vip",
    "cineplex odeon",
    "landmark cinemas",
    "movie mill",
    "stream ticket",
    "fanx",
    "expo",
    "board game cafe",
    "escape hour",
    "vr arcade",
    "axe throwing"
  ],
  "Other / Transfers": [
    "send e-tfr",
    "etransfer",
    "tfr",
    "pts",
    "to:td",
    "fee",
    "interest",
    "account fee",
    "podp",
    "investments pay",
    "deposit",
    "payroll",
    "atm",
    "withdrawal",
    "rebate",
    "refund",
    "dividend",
    "bank charge",
    "nsf",
    "cheque",
    "transfer",
    "visa payment",
    "credit card payment",
    "loan payment",
    "rent",
    "lease",
    "cra",
    "tax",
    "government",
    "pension",
    "benefit",
    "canada child",
    "cpp",
    "ei",
    "disability",
    "gst",
    "scholarship",
    "grant",
    "deposit insurance",
    "rbc",
    "td",
    "bmo",
    "cibc",
    "scotiabank",
    "atb financial",
    "servus credit union",
    "first calgary",
    "connect first",
    "desjardins",
    "wealthsimple trade",
    "tangerine bank",
    "motusbank",
    "eq bank",
    "hsbc canada",
    "manulife bank",
    "coast capital",
    "credit union",
    "interac",
    "interac e-transfer",
    "bill payment",
    "canada revenue agency",
    "tax refund",
    "cra deposit",
    "government deposit",
    "payroll deposit",
    "payroll deduction",
    "insurance refund",
    "account adjustment",
    "monthly charge",
    "overdraft",
    "bank fee",
    "visa card",
    "mastercard payment",
    "amex payment",
    "chequing",
    "savings transfer",
    "direct deposit",
    "automatic payment",
    "wire transfer"
  ]
}